apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-app
spec:
  params:
    - default: 'image-registry.openshift-image-registry.svc:5000/demo/app:latest'
      name: IMAGE
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/siamaksade/build-rhel-entitlements'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: buildah
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source
  workspaces:
    - name: source
