apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projected-resource-my-share
rules:
  - apiGroups:
      - projectedresource.storage.openshift.io
    resources:
      - shares
    resourceNames:
      - my-share
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: projected-resource-my-share
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: projected-resource-my-share
subjects:
  - kind: ServiceAccount
    name: default
    namespace: my-csi-app-namespace
